# Generated by Django 4.0.2 on 2022-02-28 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_rename_nameband_album_nameband'),
        ('music', '0002_songs_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='album.album'),
        ),
    ]
