# Generated by Django 4.0.2 on 2022-02-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('nameBand', models.CharField(max_length=150)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': ('Album',),
                'verbose_name_plural': 'Albums',
            },
        ),
    ]
