# Generated by Django 4.0.2 on 2022-02-28 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='nameBand',
            new_name='nameband',
        ),
    ]
